version: "3.9"

services:
  sonarqube:
    image: sonarqube:lts-community
    restart: always
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data 
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - term-paper

networks:
  term-paper:

volumes:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:

